export const Users = [
  {
    id:1,
    profilePicture: "asset/person/surya.jpg",
    username: "Suriya",
  },
  {
    id:2,
    profilePicture: "asset/person/vijay.jfif",
    username: "Vijay",
  },
  {
    id:3,
    profilePicture: "asset/person/vjvijay.jfif",
    username: "vj vijay",
  },
  {
    id:4,
    profilePicture: "asset/person/4.jpeg",
    username: "Dora Hawks",
  },
  {
    id:5,
    profilePicture: "asset/person/5.jpeg",
    username: "Thomas Holden",
  },
  {
    id:6,
    profilePicture: "asset/person/6.jpeg",
    username: "Shirley Beauchamp",
  },
  {
    id:7,
    profilePicture: "asset/person/7.jpeg",
    username: "Travis Bennett",
  },
  {
    id:8,
    profilePicture: "asset/person/8.jpeg",
    username: "Kristen Thomas",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "/asset/post/post 1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "/asset/post/post 2.jpeg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "/asset/post/post 3.jpeg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "/asset/post/post 4.jpeg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "/asset/post/post 5.jpeg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "/asset/post/post 6.jpeg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "/asset/post/post 7.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "/asset/post/post 8.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
];
